http:
  port: 8080
mongodb:
  host: "localhost"
  port: 27017
  db_name: "plateforme_reference"
rabbitmq:
  host: "localhost"
  port: 5672
  user: "guest"
  password: "guest"
  virtualHost: "/"
redis:
  host: "localhost"
  port: 6379